CONFIG_PM=n

CONFIG_MAIN_STACK_SIZE=10240

CONFIG_BOOT_SWAP_SAVE_ENCTLV=n
CONFIG_BOOT_ENCRYPT_IMAGE=n

CONFIG_BOOT_UPGRADE_ONLY=n
CONFIG_BOOT_BOOTSTRAP=n

### mbedTLS has its own heap
# CONFIG_HEAP_MEM_POOL_SIZE is not set

CONFIG_FLASH=y
CONFIG_STM32_MEMMAP=y
CONFIG_ARM_MPU=y

CONFIG_ICACHE=y
CONFIG_DCACHE=y

CONFIG_BBRAM=y
CONFIG_BBRAM_INIT_PRIORITY=60
CONFIG_RTC=y
CONFIG_RTC_STM32=y

CONFIG_FAULT_DUMP=2

CONFIG_BOOT_GO_HOOKS=y
### Various Zephyr boards enable features that we don't want.
# CONFIG_BT is not set
# CONFIG_I2C is not set

CONFIG_LOG=y
CONFIG_LOG_MODE_MINIMAL=y
### Ensure Zephyr logging changes don't use more resources
CONFIG_LOG_DEFAULT_LEVEL=0
### Use info log level by default
CONFIG_MCUBOOT_LOG_LEVEL_INF=y
### Decrease footprint by ~4 KB in comparison to CBPRINTF_COMPLETE=y
CONFIG_CBPRINTF_NANO=y
### Use picolibc to reduce flash usage
CONFIG_PICOLIBC=y
### Disable malloc arena because we don't need it
CONFIG_COMMON_LIBC_MALLOC_ARENA_SIZE=0
############################## CUSTOM OPTIONS ##############################
CONFIG_SPI_NOR_SFDP_RUNTIME=y
CONFIG_BOOT_SIGNATURE_KEY_FILE=""
CONFIG_BOOT_SIGNATURE_TYPE_NONE=y
CONFIG_BOOT_SWAP_USING_SCRATCH=y

CONFIG_MCUBOOT_BOOT_MAX_ALIGN=16

CONFIG_SPI=y
CONFIG_SPI_NOR=y
CONFIG_FLASH=y

CONFIG_BOOT_MAX_IMG_SECTORS_AUTO=n
CONFIG_BOOT_MAX_IMG_SECTORS=1024

CONFIG_SHELL_PROMPT_UART="mcuboot:~$ "
#CONFIG_MCUBOOT_LOG_LEVEL_DBG=y
#CONFIG_FLASH_LOG_LEVEL_DBG=y

#CONFIG_MEMC_LOG_LEVEL_DBG=y
#CONFIG_LOG_DEFAULT_LEVEL=4
#CONFIG_MPU_LOG_LEVEL_DBG=y

#CONFIG_MEMC=y
#CONFIG_STM32_MEMMAP=y
#CONFIG_MEMC_STM32_PSRAM_V2=y
#CONFIG_MEMC_STM32_OSPI_PSRAM=y


#CONFIG_MEMC=y
#CONFIG_MEMC_STM32_OSPI_PSRAM=y
#CONFIG_STM32_MEMMAP=y





#CONFIG_CACHE_MANAGEMENT=y
#CONFIG_CACHE=y
#CONFIG_ARCH_CACHE=y


#CONFIG_CLOCK_CONTROL=y
#CONFIG_CLOCK_CONTROL_STM32_CUBE=y

#CONFIG_MEM_ATTR=y
#CONFIG_ARM_MPU=y
#CONFIG_MPU_ALLOW_FLASH_WRITE=y
